### ISSUE TITLE
repeated 'invalid start byte'

### ISSUE THREAD

**Issue by kylegordon** [mikenye/docker-piaware-to-influx#20]
hi!

I think piaware2influx has a problem somewhere.... my docker logs are showing repeated messages stating the following

```
[piaware2influx] piaware2influx.py version 2020-06-05
[piaware2influx] 2020-07-22 11:57:27 [RX: 0, TX: 0, V: 0] CONNECT: Connecting to 172.24.32.11:30005 to receive dump1090 TCP BaseStation output data
[piaware2influx] 2020-07-22 11:57:27 [RX: 0, TX: 0, V: 0] CONNECT: Connected OK, receiving data
[piaware2influx] Traceback (most recent call last):
[piaware2influx]   File "/piaware2influx.py", line 834, in <module>
[piaware2influx]     D.add_data_to_buffer(data.decode("utf-8"))
[piaware2influx] UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 21: invalid start byte
[piaware2influx] Namespace(dump1090_port='30005', dump1090_server='172.24.32.11', telegraf_url='http://127.0.0.1:8186/write', verbose=False)
```

This is the snippet from my docker-compose.yml

```
  piaware2influx:
    # Credit to https://github.com/mikenye/docker-piaware-to-influx
    image: mikenye/piaware-to-influx:latest
    tty: true
    container_name: piaware2influx
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - INFLUXDB_URL=http://172.24.32.13:8086
      - DUMP1090_HOST=${BEASTHOST}
      - DUMP1090_PORT=${BEASTPORT}
      - VERBOSE_LOGGING=False
```

BEASTPORT and BEASTHOST are just defined in .env as...

```
BEASTHOST=172.24.32.11
BEASTPORT=30005
```

Not sure if it's a formatting error on my part or something internal at fault? Happy to dig around with some guidance. The sending system is just readsb:latest on a BananaPi M2 Zero.
